# Generated by Django 5.0.4 on 2024-04-18 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='menu_item_image',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='ordereditem',
            name='ordered_item_image',
            field=models.URLField(blank=True),
        ),
    ]
