# Generated by Django 5.0.4 on 2024-04-19 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_remove_cart_customer_remove_order_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_mobile_number',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_user_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
